version: '3.7'
services: 
  backend: 
    build: 
      context: .
      dockerfile: Dockerfile
    image: tax-reports:1 
    ports:
      - '8080:8080'
  database: 
    image: mysql:latest
    volumes:
      - /var/lib/mysql
      - ./src/main/resources/init:/docker-entrypoint-initdb.d
    restart: always
    environment: 
      MYSQL_DATABASE: 'Tax'
      MYSQL_USER: 'root'
      MYSQL_ROOT_PASSWORD: '12345678'
    ports:
      - '3306:3306'
    expose:
      - '3306'
